_prefs: 
  mapid: pratikyadav.f637d67e
  saveCenter: false
_properties: {}
attribution: "<a href='http://mapbox.com/about/maps' target='_blank'>Terms & Feedback</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -82.9688
  - 16.8466
  - 4
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Pirates Return
source: "mapbox:///mapbox.mapbox-streets-v4,pratikyadav.ef579a16,pratikyadav.c875cc85,pratikyadav.b579be39"
styles: 
  - style.mss
  - labels.mss
template: ''
